language: python
python:
    - "3.6"
services:
    - postgresql
env:
    global:
        - SECRET_KEY=secret
        - TGAUTH_BOT=
        - TGAUTH_DOMAIN=
        - TGAUTH_WEBHOOK_SUFFIX=
        - TELEGRAM_TOKEN=
        - MAPBOX_TOKEN=
        - SOCIAL_AUTH_FACEBOOK_KEY=
        - SOCIAL_AUTH_FACEBOOK_SECRET=
script:
    - ./manage.py test
    - ./manage.py behave -k -S -f allure
